CREATE TABLE IF NOT EXISTS process_def (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_code VARCHAR(128) NOT NULL DEFAULT '',
    proc_name VARCHAR(64) NOT NULL DEFAULT '',
    biz_proc_code VARCHAR(128) NOT NULL DEFAULT '',
    version VARCHAR(31) NOT NULL DEFAULT '',
    proc_type VARCHAR(32) NOT NULL DEFAULT '',
    proc_type_name VARCHAR(64) NOT NULL DEFAULT '',
    business_code VARCHAR(31) NOT NULL DEFAULT '',
    data_packet_resolver_class VARCHAR(1024) NOT NULL DEFAULT '',
    pre_check_config CLOB,
    is_delete TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    packet_init_config CLOB,
    init_inst_data VARCHAR(255) NOT NULL DEFAULT '',
    init_params VARCHAR(256) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_process_def_code ON process_def(proc_code);

CREATE TABLE IF NOT EXISTS process_task_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_def_id BIGINT NOT NULL DEFAULT 0,
    process_code VARCHAR(255) NOT NULL DEFAULT '',
    task_code VARCHAR(64) NOT NULL DEFAULT '',
    condition VARCHAR(255) NOT NULL DEFAULT '',
    `key` VARCHAR(32) NOT NULL DEFAULT '',
    `value` CLOB NOT NULL,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_task_config_proc ON process_task_config(process_def_id, task_code);
CREATE INDEX IF NOT EXISTS idx_process_task_config_process_code ON process_task_config(process_code, task_code);

CREATE TABLE IF NOT EXISTS process_inst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_def_id BIGINT NOT NULL DEFAULT 0,
    proc_name VARCHAR(64) NOT NULL DEFAULT '',
    business_code VARCHAR(31) NOT NULL DEFAULT '',
    city_operate_mode VARCHAR(31) NOT NULL DEFAULT 'INNER_DIRECT',
    relate_proc_inst_id BIGINT NOT NULL DEFAULT 0,
    relate_task_inst_id BIGINT NOT NULL DEFAULT 0,
    main_proc_inst_id BIGINT NOT NULL DEFAULT 0,
    parent_proc_inst_id BIGINT NOT NULL DEFAULT 0,
    derived_proc_inst_id BIGINT NOT NULL DEFAULT 0,
    process_candidates VARCHAR(256) NOT NULL DEFAULT '',
    cancel_task_name VARCHAR(20) NOT NULL DEFAULT '',
    cancel_code INT NOT NULL DEFAULT 0,
    cancel_reason VARCHAR(1024) NOT NULL DEFAULT '',
    start_user VARCHAR(64) NOT NULL DEFAULT '',
    start_user_ke_id VARCHAR(20) NOT NULL DEFAULT '0',
    status TINYINT NOT NULL DEFAULT 0,
    end_reason VARCHAR(64) NOT NULL DEFAULT '',
    proc_type VARCHAR(31) NOT NULL DEFAULT '',
    biz_scene VARCHAR(31) NOT NULL DEFAULT '',
    proc_desc VARCHAR(1024) NOT NULL DEFAULT '',
    city_code INT NOT NULL DEFAULT 0,
    source VARCHAR(128) NOT NULL DEFAULT '',
    start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_inst_proc_def_id ON process_inst(proc_def_id);
CREATE INDEX IF NOT EXISTS idx_process_inst_relate_proc_inst_id ON process_inst(relate_proc_inst_id);
CREATE INDEX IF NOT EXISTS idx_process_inst_relate_task_inst_id ON process_inst(relate_task_inst_id);

CREATE TABLE IF NOT EXISTS process_inst_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    `key` VARCHAR(64) NOT NULL DEFAULT '',
    key_cn VARCHAR(64) NOT NULL DEFAULT '',
    `value` VARCHAR(2000) NOT NULL DEFAULT '',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_inst_data_proc_inst_id ON process_inst_data(proc_inst_id);

CREATE TABLE IF NOT EXISTS process_inst_data_init_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_def_id BIGINT NOT NULL DEFAULT 0,
    city_code VARCHAR(16) NOT NULL DEFAULT '',
    `key` VARCHAR(64) NOT NULL DEFAULT '',
    `value` VARCHAR(1024) NOT NULL DEFAULT '',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_inst_data_init_config_proc ON process_inst_data_init_config(proc_def_id, city_code);

CREATE TABLE IF NOT EXISTS process_inst_data_packet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    data_packet_value_id BIGINT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_packet_proc_inst_id ON process_inst_data_packet(proc_inst_id);

CREATE TABLE IF NOT EXISTS process_inst_data_packet_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    proc_task_inst_id BIGINT NOT NULL DEFAULT 0,
    task_code VARCHAR(64) NOT NULL DEFAULT '',
    init_value CLOB,
    `value` CLOB,
    init_source CLOB,
    source CLOB,
    status TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_packet_value_proc_task ON process_inst_data_packet_value(proc_inst_id, proc_task_inst_id);
CREATE INDEX IF NOT EXISTS idx_packet_value_proc_task_code ON process_inst_data_packet_value(proc_inst_id, task_code);

CREATE TABLE IF NOT EXISTS process_inst_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_inst_id BIGINT NOT NULL DEFAULT 0,
    relation_code VARCHAR(64) NOT NULL DEFAULT '',
    relation_type VARCHAR(64) NOT NULL DEFAULT '',
    relation_inst_id VARCHAR(64) NOT NULL DEFAULT '',
    process_def_id BIGINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_inst_relation_process_inst_id ON process_inst_relation(process_inst_id);
CREATE INDEX IF NOT EXISTS idx_process_inst_relation_relation ON process_inst_relation(relation_type, relation_code, relation_inst_id);

CREATE TABLE IF NOT EXISTS process_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    task_inst_id BIGINT NOT NULL DEFAULT 0,
    stage VARCHAR(32) NOT NULL DEFAULT '',
    result VARCHAR(32) NOT NULL DEFAULT '',
    content VARCHAR(2000) NOT NULL DEFAULT '',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_log_inst ON process_log(proc_inst_id, task_inst_id);

CREATE TABLE IF NOT EXISTS process_task_inst (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    task_code VARCHAR(64) NOT NULL DEFAULT '',
    task_name VARCHAR(128) NOT NULL DEFAULT '',
    request_id VARCHAR(64) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 0,
    operator_id BIGINT NOT NULL DEFAULT 0,
    operator_name VARCHAR(20) NOT NULL DEFAULT '',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uniq_process_task_inst_request_id ON process_task_inst(request_id);
CREATE INDEX IF NOT EXISTS idx_process_task_inst_proc_code ON process_task_inst(proc_inst_id, task_code);

CREATE TABLE IF NOT EXISTS process_task_inst_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_task_inst_id BIGINT NOT NULL DEFAULT 0,
    `key` VARCHAR(64) NOT NULL DEFAULT '',
    key_cn VARCHAR(64) NOT NULL DEFAULT '',
    `value` VARCHAR(2000) NOT NULL DEFAULT '',
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_process_task_inst_data_proc ON process_task_inst_data(proc_task_inst_id);

CREATE TABLE IF NOT EXISTS process_task_inst_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_inst_id BIGINT NOT NULL DEFAULT 0,
    relation_type VARCHAR(64) NOT NULL DEFAULT '',
    relation_inst_id VARCHAR(128) NOT NULL DEFAULT '',
    status TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_task_relation_task_type_inst ON process_task_inst_relation(task_inst_id, relation_type, relation_inst_id);
CREATE INDEX IF NOT EXISTS idx_task_relation_task_inst_id ON process_task_inst_relation(task_inst_id);
CREATE INDEX IF NOT EXISTS idx_task_relation_external ON process_task_inst_relation(relation_type, relation_inst_id);

CREATE TABLE IF NOT EXISTS process_task_inst_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    proc_task_inst_id BIGINT NOT NULL DEFAULT 0,
    ucid VARCHAR(64) NOT NULL DEFAULT '',
    code VARCHAR(64) NOT NULL DEFAULT '',
    name VARCHAR(64) NOT NULL DEFAULT '',
    is_delete TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_task_candidate_proc_inst_id ON process_task_inst_candidate(proc_inst_id);
CREATE INDEX IF NOT EXISTS idx_task_candidate_task_inst_id ON process_task_inst_candidate(proc_task_inst_id);

CREATE TABLE IF NOT EXISTS candidate_inst_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proc_inst_id BIGINT NOT NULL DEFAULT 0,
    relate_inst_id VARCHAR(64) NOT NULL DEFAULT '0',
    ucid VARCHAR(64) NOT NULL DEFAULT '',
    code VARCHAR(64) NOT NULL DEFAULT '',
    name VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT NOT NULL DEFAULT 0,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `type` INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 0,
    task_name VARCHAR(31) NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_candidate_inst_relation_proc_inst_id ON candidate_inst_relation(proc_inst_id);
CREATE INDEX IF NOT EXISTS idx_candidate_inst_relation_relate_inst_id ON candidate_inst_relation(relate_inst_id);

CREATE TABLE IF NOT EXISTS event_record (
    event_id BIGINT PRIMARY KEY,
    event_type VARCHAR(255) NOT NULL DEFAULT '',
    payload_class VARCHAR(512) NOT NULL DEFAULT '',
    payload CLOB NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    subject_type VARCHAR(64) NOT NULL DEFAULT '',
    subject_id VARCHAR(128) NOT NULL DEFAULT '',
    partition_key VARCHAR(128) NOT NULL DEFAULT '',
    correlation_id VARCHAR(128) NOT NULL DEFAULT '',
    causation_event_id BIGINT,
    status VARCHAR(32) NOT NULL DEFAULT '',
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    dispatched_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_record_status ON event_record(status, event_id);
CREATE INDEX IF NOT EXISTS idx_event_record_partition ON event_record(partition_key, event_id);

CREATE TABLE IF NOT EXISTS event_delivery (
    event_id BIGINT NOT NULL,
    listener_name VARCHAR(128) NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT '',
    attempts INT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error CLOB,
    ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (event_id, listener_name)
);

CREATE INDEX IF NOT EXISTS idx_event_delivery_due ON event_delivery(status, next_attempt_at, event_id);
